# Generated by Django 4.0.4 on 2022-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_cadeira_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ects',
            field=models.IntegerField(default=0),
        ),
    ]
