# Generated by Django 4.0.4 on 2022-05-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projetohobby_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetohobby',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='projetos_hobby/'),
        ),
    ]
