# Generated by Django 4.0.4 on 2022-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_cadeira_ects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='educacao/')),
                ('anos', models.CharField(max_length=100)),
                ('certificacaoNivel', models.IntegerField()),
            ],
        ),
    ]
