# Generated by Django 4.0.4 on 2022-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projetohobby_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('avaliacao', models.CharField(max_length=2)),
                ('imagem', models.ImageField(blank=True, upload_to='comentarios/')),
                ('link', models.URLField(blank=True)),
                ('autor', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('acronimo', models.CharField(blank=True, max_length=100, null=True)),
                ('anoCriacao', models.CharField(max_length=4)),
                ('criador', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('presentationlayer', models.CharField(max_length=100)),
                ('logotipo', models.ImageField(blank=True, upload_to='tecnologias/')),
                ('data', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('formaUso', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
