# Generated by Django 4.0.4 on 2022-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_educacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacao',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
