# Generated by Django 4.0.4 on 2022-05-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_educacao_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='certificacao/')),
                ('data', models.DateTimeField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
