# Generated by Django 4.0.4 on 2022-05-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_tecnologia_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='noticias/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='link',
            field=models.URLField(),
        ),
    ]
