# Generated by Django 4.0.4 on 2022-05-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_noticia_alter_laboratorio_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='link',
        ),
    ]
