# Generated by Django 4.0.4 on 2022-06-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_comentario_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='TFCs/')),
                ('video', models.URLField(blank=True)),
                ('relatorio', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('aluno', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='portfolio.professor')),
            ],
        ),
    ]
